Animation
siddhi-244/Embellish pull request #335
Opened 2023-02-02 10:23 UTC by niladrix719

## What is the change?
Added a new Component under a new category added by me which is animations

## Related issue?
closes: #329 

## How was it tested?
Test in local machine

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

![cube](https://user-images.githubusercontent.com/91966855/216298718-57864b5f-d73e-4444-9e44-a489702a210b.gif)

2023-02-03 05:49 UTC, siddhi-244 requested changes
Add it in background folder as it seems to be a background animation.  Don't make a new folder

2023-02-03 05:52 UTC, niladrix719 commented
> Add it in background folder as it seems to be a background animation. Don't make a new folder

ok

2023-02-03 06:43 UTC, niladrix719 commented
> Add it in background folder as it seems to be a background animation. Don't make a new folder

moved everything

2023-02-04 16:06 UTC, siddhi-244 approved these changes

2023-02-04 16:06 UTC, merged